name: Crear Ejecutable Multiplataforma

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Crear ejecutable
        shell: bash
        run: |
          # Extraemos versión del tag (quitando la 'v')
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Generando ejecutable versión: $VERSION"

          if [ "$RUNNER_OS" == "Windows" ]; then
            ICON="assets/icon.ico"
            python -m PyInstaller \
              --onefile \
              --console \
              --clean \
              --icon="$ICON" \
              --name "Generador_Calendario_${VERSION}_Windows" \
              main.py

          elif [ "$RUNNER_OS" == "macOS" ]; then
            ICON="assets/icon.icns"
            python -m PyInstaller \
              --onefile \
              --console \
              --clean \
              --icon="$ICON" \
              --name "Generador_Calendario_${VERSION}_macOS" \
              main.py

          else
            ICON="assets/icon.png"
            python -m PyInstaller \
              --onefile \
              --console \
              --clean \
              --icon="$ICON" \
              --name "Generador_Calendario_${VERSION}_Linux" \
              main.py
          fi

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCES_TOKEN }}
