name: Crear Ejecutable Windows

on:
  push:
    tags:
      - 'v*' # Se activa cuando subes un tag que empieza por 'v' (ej: v1.1.0)

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: Descargar código
          uses: actions/checkout@v4
          with:
            python-version: '3.13'
        
        - name: Instalar dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Crear ejecutable con PyInstaller
          shell: bash
          run: |
            # Extraemos la versión del tag (removiendo la 'v' inicial)
            VERSION=${GITHUB_REF#refs/tags/}
            echo "Generando ejecutable para la versión: $VERSION"
            python -m PyInstaller --onefile --console --clean --icon="calendario.ico" --name "Generador_Calendario_$VERSION" main.py
        
        - name: Crear Release en GitHub
          uses: softprops/action-gh-release@v1
          with:
            files: dist/Generador_Calendario_*.exe
            name: Release ${{ github.ref_name }}
            tag_name: ${{ github.ref }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}